"""
This script inputs the CSV file generated by csv_to_player_stats.py and outputs a summary stats. It calculates the average of each numeric column (excluding 'Player'), 
the total number of games, and total moves from the input CSV file, and saves these statistics in a new CSV file. 
"""

import pandas as pd
import os

def calculate_statistics(input_csv_path):
    # Read the CSV file, exclude non-numeric columns
    df = pd.read_csv(input_csv_path).select_dtypes(include='number')

    # Calculating the averages and standard deviations for each column
    averages = df.mean()
    standard_deviations = df.std()

    # Calculating the total number of games and total moves
    total_games = df['total_game_count'].sum()
    total_moves = df['total_moves'].sum()

    # Creating a new DataFrame for the output
    output_df = pd.DataFrame([averages, standard_deviations], index=['Average', 'Standard Deviation'])
    output_df['total_game_count'] = total_games
    output_df['total_moves'] = total_moves

    return output_df

def main():
    input_csv_path = ''
    output_dir = ''
    output_csv_file_name = 'summarized_player_data.csv'

    output_df = calculate_statistics(input_csv_path)
    output_csv_path = os.path.join(output_dir, output_csv_file_name)
    output_df.to_csv(output_csv_path, index=True)
    
if __name__ == "__main__":
    main()
